### ISSUE TITLE
Option to set number of results

### ISSUE THREAD

**Issue by elhoim** [digital4rensics/Malformity#12]
Have an option to set the number of results returned by ISC Passive DNS database

When having an API Key, it is possible to query for more than 10.000 results back, by default the API caps at 10K

**Comment by digital4rensics** [comment]
Thanks for adding this one. Was on my personal to-do, getting 10k results pretty much kills Maltego :-)

**Comment by elhoim** [comment]
The downsides of XML and Java overhead i suppose.
I can test it on a machine with 16GB of RAM and a buffer set in maltego of 8192 to see how it goes with Big Data like 10,000 records

**Comment by digital4rensics** [comment]
Currently, there is no built-in Maltego support for respecting result limits in Local Transforms. I'm kicking around a few ideas for implementing it in the transform code.

**Comment by elhoim** [comment]
Are you sure about that?
Under the Investigate tab, there is a slider "Number of Results" with values 10, 50, 255, 10k.
At http://ctas.paterva.com/view/Userguide#Setting_the_number_of_results_returned they mention:
<< _In upcoming versions of the tool the transforms will be categorized as either ‘enumeration’ or ‘search’ transforms – the slider will only apply to ‘search’ transforms. For now you have to be careful to understand how the slider works and spend time experimenting with it._ >>

**Comment by digital4rensics** [comment]
As far as I know, that slider is valid for transforms on a TAS, and currently not supported for local transforms. Nadeem stated that Maltego doesn't currently accept a parameter for it. I'll keep looking in to it.

**Comment by krmaxwell** [comment]
Does the new framework / interface / whatevs accept this sort of parameter now?

**Comment by digital4rensics** [comment]
No, it's a remote transform only feature.

**Comment by digital4rensics** [comment]
Tungsten seems to have auto-fixed this as results are now limited with the slider auto-magically. Let me know if others don't see the same functionality.
