### ISSUE TITLE
Search Team-Cymru Malware Hash Registry

### ISSUE THREAD

**Issue by elhoim** [digital4rensics/Malformity#15]
http://www.team-cymru.org/Services/MHR/

**Comment by digital4rensics** [comment]
I've requested permission from Team CYMRU to include the service as a transform. I'm waiting on a response prior to moving forward.

**Comment by digital4rensics** [comment]
Implemented in cymru_hashcheck.py. The transform updates the original hash and displays whether or not it was detected, and if so, the date and percentage detection rate.
