### ISSUE TITLE
SANS ISC data reports

### ISSUE THREAD

**Issue by elhoim** [digital4rensics/Malformity#19]
Based on data from volunteers running SANS sensors

Report per AS: https://isc.sans.edu/as.html

Report per IP: https://isc.sans.edu/ipdetails.html?ip=069.175.126.170

There are other reporst but i dont think they could be interesting - https://isc.sans.edu/reports.html

**Comment by digital4rensics** [comment]
Implemented ISC IP and AS report transforms. IP report returns targeted ports and protocols. AS report returns all tracked IPs from the AS.
