### ISSUE TITLE
Transforms menu is empty

### ISSUE THREAD

**Issue by wychw00d** [digital4rensics/Malformity#22]
Across 2 separate installs using different platforms, Malformity appears to succeed, and entities are available, but no transforms can be run, as they are not found in the context menu.  What could be the issue?

**Comment by digital4rensics** [comment]
Was Maltego open when you installed Malformity? If so, please close Maltego, and run the Canari install again. Maltego won't recognize the new transforms if it's open when run.

Also, do you have multiple versions installed on the same machine? If so, please ensure you're selecting the same instance that you're running to install them to.

Thanks and let me know if that doesn't work!

**Comment by wychw00d** [comment]
I was not running Maltego during this install, and actually restarted from a fresh VM snapshot without Canari, and repeated the install following this guide.  To be clear, I simply used the approach of install, start/quit, install, not the step-by-step.

http://forums.canariproject.com/index.php?p=/discussion/15/sploitegometasploit-transform-testers-needed/p1

If I Manage Transforms, they are there, however they do not ever populate the contextual menu for entities added by Malformity.  I do, however, retain transforms for Paterva/stock entities.

**Comment by digital4rensics** [comment]
Ok, so if I understand, if you place an IPv4 entity on the graph and right click, the Malformity transforms don't appear as option?

What version OS are you running? Could you also check the Canari version?

Thanks.

**Comment by wychw00d** [comment]
I'm running a github clone of the latest Canari build - commit dbee1aface0c2e5f8132a18f16730034de13c8d9 on BT5r3.

**Comment by digital4rensics** [comment]
Ok, I'll check with @allfro to see if the new versions of Canari could have broken something. The latest Canari build is .7 and Malformity is running on .5. I need to get it updated and tested for the new Canari versions.

**Comment by digital4rensics** [comment]
Nadeem stated there was a known issue with one shortly-lived canari version. Would you be able to post this issue on the CanariProject forums so that we can both troubleshoot it together?

Thanks!

**Comment by allfro** [comment]
Did you run Maltego for the first time and complete the initialization wizard? That's absolutely critical otherwise you will have that problem. Looks like you might have initialized it half-way and it got interrupted somehow. Try `rm -rf ~/.maltego` and re-initialize Maltego again before attempting to install the transforms again.

**Comment by digital4rensics** [comment]
Is this issue still persisting @wychw00d ? If not, please let me know so that I can close it.

Thanks.

**Comment by digital4rensics** [comment]
Haven't heard anything. If issue re-occurs, please re-open.
