### ISSUE TITLE
pDNS

### ISSUE THREAD

**Issue by r3comp1le** [digital4rensics/Malformity#27]
Use wildcard when searching for domain.

domain.com --> search for *.domain.com

**Comment by digital4rensics** [comment]
Are you running the latest version of Malformity?

If so, there is a transform called "Wildcard domain search" which will accept *.domain.com and return all results for domain.com.

Please confirm so I can close the issue. Thanks!

**Comment by r3comp1le** [comment]
ok thanks. Looks like the update added that 3rd transform.  Is there a way in the code to default ALL domains to be *.domain?

**Comment by r3comp1le** [comment]
I dont expect this to be a request for a pull, rather a custom one for my circumstance.

**Comment by digital4rensics** [comment]
If you want to do that, you should be able to alter that transform with something like domain = '*."+request.value which would then assign the *. automatically to every domain run with the Wildcard Domain Search.

Let me know if that works out.

**Comment by r3comp1le** [comment]
worked great, thanks!

NOTES:

-create-transform
-setup.py install
-canari install-package malformity
