### ISSUE TITLE
VT API key

### ISSUE THREAD

**Issue by hiddenillusion** [digital4rensics/Malformity#28]
Malformity / src / Malformity / transforms / common / vt.py 
line 40 should read:
  privkey = config['virustotal/apikey']

**Comment by digital4rensics** [comment]
Hey Glenn,

This was raised a few minutes ago by someone else. The file that has the issue is actually .canari since I need to update the VT section of that. It'll allow people to run two separate API keys, one for public API use and one for Private API use.

I use both, some may only use one, and many can't use the Private API, which is why I'm keeping them separate.

Thoughts?

**Comment by hiddenillusion** [comment]
I'll admit I haven't spend a great deal of time within Maltego and your
Malformity so this was just something that came up as I was trying to do
the install and the quick trace came back to just changing that line -
unless I needed to change it somewhere else.  What your saying about the
private/public API queries makes sense for sure though.

On Wed, May 15, 2013 at 5:12 PM, digital4rensics
notifications@github.comwrote:

> Hey Glenn,
> 
> This was raised a few minutes ago by someone else. The file that has the
> issue is actually .canari since I need to update the VT section of that.
> It'll allow people to run two separate API keys, one for public API use and
> one for Private API use.
> 
> I use both, some may only use one, and many can't use the Private API,
> which is why I'm keeping them separate.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digital4rensics/Malformity/issues/28#issuecomment-17966622
> .

## 

Glenn Edwards
@hiddenillusion

**Comment by digital4rensics** [comment]
Yea, it'll work as a temp fix for changing that. The other option prior to me getting the fix up is to cd to .canari and edit Malformity.conf to include an entry for the privkey in the config as well.

**Comment by digital4rensics** [comment]
Should be all fixed!
