### ISSUE TITLE
UA Verification

### ISSUE THREAD

**Issue by digital4rensics** [digital4rensics/Malformity#8]
Write an Xform for using the useragentstring.com API to verify UAs.

**Comment by krmaxwell** [comment]
What would the results of this transform look like? Give it a Phrase (the actual User-Agent string) and get back a bunch of key-value pairs that you'd represent as... what, exactly?

**Comment by digital4rensics** [comment]
Initial plan was to provide it the UA (can't remember offhand if I have a entity for that) and it would add a property with a Valid: yes/no type response.

**Comment by digital4rensics** [comment]
Looked in to it & not sure the data set is conducive. Closing for now.
